### ISSUE TITLE
Merge with Plots.jl

### ISSUE THREAD

**Issue by not7cd** [JuliaPlots/PlotDocs.jl#127]
Hi, I wonder why Plots.jl is split from it's documentation. I haven't found any issue relating to this.
As I see this now, docs are 1 month behind main project. Is there a reason to keep that this way?

If not, is there a possibility to merge this with main project? My point is that it's harder to improve on docs when they are hidden here. Also I wish to improve on docs, and that might require creation of docstrings in source.

**Comment by mkborregaard** [comment]
That's because the documentation is, or used to be, for the whole org - StatsPlots, GraphRecipes, RecipesBase and Plots. This is the common approach for the julia orgs.

**Comment by ChrisRackauckas** [comment]
Also, this is a gigantic repo because it happens to contain a lot of plots and animations.

**Comment by mkborregaard** [comment]
If you do need docstrings for anything they are available as `@doc myfunction`
