### ISSUE TITLE
Broken figure in documentation

### ISSUE THREAD

**Issue by logankilpatrick** [JuliaPlots/PlotDocs.jl#137]
Repost of this issue: https://github.com/JuliaPlots/Plots.jl/issues/2021

**Comment by nlw0** [comment]
When I first reported the issue the three smaller graphs were not even showing up, the figure was a mess. I didn't think of taking a screenshot. Now the smaller subplots are just looking too small.

**Comment by daschw** [comment]
OK, got it, thanks!

**Comment by daschw** [comment]
Seems to be fixed.
