### ISSUE TITLE
Searching for Aspect Ratio isn't helpful

### ISSUE THREAD

**Issue by jessebett** [JuliaPlots/PlotDocs.jl#199]
Searching for `aspect` or `ratio` does not return anything helpful about the `aspect_ratio` attribute.

**Comment by BeastyBlacksmith** [comment]
ref: https://github.com/JuliaPlots/Plots.jl/issues/2337

**Comment by jessebett** [comment]
Also it turns out aspect ratio isn't even what I wanted, it was `size`.
