### ISSUE TITLE
png is not default plot type

### ISSUE THREAD

**Issue by travigd** [JuliaPlots/PlotDocs.jl#220]
Docs say that png is the default type, but using the default GR backend (at least in Jupyter) outputs in SVG format.

**Comment by BeastyBlacksmith** [comment]
Thats something that IJulia does. It always displays the richest available display, IIRC. Does that also affect `savefig`?

**Comment by travigd** [comment]
IJulia packages all of the display types together and sends them to the frontend, and the frontend chooses the richest type available. In this case, IJulia is only sending SVG (when generically it would send both SVG **and** PNG, though obviously that can be wasteful).

**Comment by BeastyBlacksmith** [comment]
The exact handling for Plots is [here](https://github.com/JuliaPlots/Plots.jl/blob/7fe6a69a216fea9feb4be201b1d78ad11a83af0c/src/ijulia.jl#L39).

**Comment by travigd** [comment]
Thanks. That pretty much confirms what I'm saying: png is not the default plot type when using IJulia. It's dependent on the backend (with SVG seeming to be the default).

**Comment by BeastyBlacksmith** [comment]
The docs could be indeed be more precise here: the default display type may vary depending on the environment, the default output type (what you get from `savefig("myplot")`) should always be `.png`.
