### ISSUE TITLE
Gaston multiplot fails in CI

### ISSUE THREAD

**Issue by t-bltg** [JuliaPlots/PlotDocs.jl#252]
When I run [ref17](https://docs.juliaplots.org/latest/generated/gaston/#gaston-ref17) locally, I get, as expected:

```julia
using Plots; gaston()

main() = begin
  plot(Plots.fakedata(100, 10), layout=4, palette=cgrad.([:grays :blues :heat :lightrainbow]), bg_inside=[:orange :pink :darkblue :black])
  png("ref17")
end

main()
```

![ex](https://user-images.githubusercontent.com/13423344/127386779-de8d709b-0287-4352-98dd-17117ccb00b7.png)

This is different from the CI generated [image](https://docs.juliaplots.org/latest/generated/gaston_ex17.png), where obviously the multiplot layout fails:
![gaston_ex17](https://user-images.githubusercontent.com/13423344/127386871-f6632fc6-c681-4e4b-a5dd-c057253996d6.png)

@isentropic, any idea what might cause this ?

**Comment by isentropic** [comment]
I'm not exactly sure, does it work normal when not in tests? Like, if you do it manually does it look the same?

**Comment by t-bltg** [comment]
> I'm not exactly sure, does it work normal when not in tests? Like, if you do it manually does it look the same? I mean, in case you plot from REPL, save onto some png file, and open that file?

Yes, run the mwe yourself with the code [here](https://github.com/JuliaPlots/PlotDocs.jl/issues/252#issue-955185752) and you'll get my first image, which is correct.

We don't have any [multiplot](http://gnuplot.sourceforge.net/demo/layout.html) commands in `gaston.jl` for defining the axes  because `Plots` handles the layout, not `Gaston/gnuplot`.

**Comment by t-bltg** [comment]
The first plot looks OK, only the other ones seem to suffer from a wrong scaling ...

**Comment by t-bltg** [comment]
I've made progress, the [backend plot](http://docs.juliaplots.org/latest/backends/) now looks like this :
![backends_gaston](https://user-images.githubusercontent.com/13423344/127649856-fbb6768b-00f0-4c5d-a71c-c8ea7412ce91.png)

**Comment by t-bltg** [comment]
Fixed in master.
