### ISSUE TITLE
The getting started code throws error

### ISSUE THREAD

**Issue by layne-sadler** [JuliaPlots/PlotDocs.jl#258]
The first block of code on the documentation getting started doesn't run.

```
gif undefined
```
`VERSION v"1.6.1"`

**Comment by BeastyBlacksmith** [comment]
the first block of code of "Getting Started" is 
```julia
import Pkg
Pkg.add("Plots")
```
can you provide the full error message?

**Comment by layne-sadler** [comment]
I think I was doing the "Getting Started/ tutorial" without doing "Installation" first; thinking that the Plots library was built-in to Julia. 

"Be sure to run the Installation steps before this tutorial."
http://docs.juliaplots.org/latest/tutorial/
