### ISSUE TITLE
legend_position values are not documented

### ISSUE THREAD

**Issue by NLaws** [JuliaPlots/PlotDocs.jl#262]
I cannot find what values are permitted for `legend_position`. The documentation says that GR supports `legend_position` but when I include it in a `plot` command (with some trial and error values like "left" and :left) the legend does not change position. For example:
```julia
plot(x, y, legend_position="left")
```

**Comment by BeastyBlacksmith** [comment]
```julia
plot(1:3, legend_position=:left)
```
works fine for me on Plots v1.23.6, what is your version?

**Comment by BeastyBlacksmith** [comment]
fixed by https://github.com/JuliaPlots/Plots.jl/commit/1bdec476c3b7e7e30d2b440e28a640c4ff75d89a

**Comment by NLaws** [comment]
I was on 1.22.5 (not sure why since I created the project just a week ago). `] up Plots` brought me to 1.23.2 (on Julia 1.6.3)
