### ISSUE TITLE
Add link to the project description

### ISSUE THREAD

**Issue by waldyrious** [JuliaPlots/PlotDocs.jl#28]
Github has a field for a project description and a link, in the main page of the repo. http://juliaplots.github.io/ should be added there.

**Comment by waldyrious** [comment]
@mkborregaard ping :)

**Comment by mkborregaard** [comment]
Sorry, what do you mean? Could you make a PR?

**Comment by waldyrious** [comment]
I can't unfortunately. This has to be changed directly in the Github interface by an owner/admin of the repo.

You should be able to just click the "Edit" button next to the repository title in https://github.com/JuliaPlots/PlotDocs.jl, and paste the URL in the second text field that will appear.

**Comment by mkborregaard** [comment]
Cool, thanks.
