### ISSUE TITLE
join GSoD'22?

### ISSUE THREAD

**Issue by johnnychen94** [JuliaPlots/PlotDocs.jl#280]
It would be a good opportunity to join [GSoD](https://julialang.org/jsoc/gsod/projects/) this year to fulfill [the new demo galleries](https://docs.juliaplots.org/dev/user_gallery/). Thoughts?

@logankilpatrick will this be too lazy for this year?

cc: @t-bltg @BeastyBlacksmith

**Comment by logankilpatrick** [comment]
I can try and help get this going, the application is due in 2 days so I'm going to need help from the plots folks to write this up. If someone can do that, I can help get the proposal in.

**Comment by BeastyBlacksmith** [comment]
I can help writing something, probably best to hit me on zulip with the details
