### ISSUE TITLE
"Edit this page" links point to wrong URLs

### ISSUE THREAD

**Issue by waldyrious** [JuliaPlots/PlotDocs.jl#29]
For example, in the [main page](https://juliaplots.github.io/), the pencil icon points to https://github.com/JuliaPlots/Plots.jl/edit/master/docs/index.md, which is a 404.

**Comment by daschw** [comment]
I think that's fixed by https://github.com/JuliaPlots/PlotDocs.jl/pull/49, right @ChrisRackauckas ?

**Comment by ChrisRackauckas** [comment]
Yes. Having to play around with it to get it working along with having the Github logo on the top correct, but it's essentially there.
