### ISSUE TITLE
Copyright notice and license

### ISSUE THREAD

**Issue by eveydee** [JuliaPlots/PlotDocs.jl#30]
There is a copyright notice in the footer: "Copyright © 2015-2016 Thomas Breloff". The first minor issue here is that it is outdated. But since there is no mention of it, it also seems to suggest that the docs themselves are not under a permissive license, even though `LICENSE` states that the software is under MIT. This is a slight contradiction in spirit, I think. Is it intentional or are the docs intended to be licensed under a CC license?

`LICENSE` itself is also outdated and displays "copyright 2016". Maybe the copyright notice should be updated automatically when the site is built?

**Comment by mkborregaard** [comment]
@tbreloff

**Comment by mkborregaard** [comment]
I'll just add my 5c. The copyright along with name and year is part of the MIT license. If you think there's a contradiction there, this is not the right place to discuss it. I don't think the year needs to be updated every time the site is built. You're welcome to submit a PR changing the dates to 2015-2017, I'd definitely merge it.
I hope you are OK with closing this.
