### ISSUE TITLE
Legend not well documented

### ISSUE THREAD

**Issue by elsoroka** [JuliaPlots/PlotDocs.jl#304]
Either there is no documentation for working with the plot legend, or it is not findable.
For example, setting the legend position (`topright`, `:bottom`, etc) is not explained.

**Comment by BeastyBlacksmith** [comment]
It's documented under `legend_position` here: https://docs.juliaplots.org/stable/generated/attributes_subplot/
Not saying, it couldn't be better. Also the text seems to get cropped.
