### ISSUE TITLE
All attributes manuals are broken

### ISSUE THREAD

**Issue by rmsmsgood** [JuliaPlots/PlotDocs.jl#312]
Series Attributes: https://docs.juliaplots.org/stable/generated/attributes_series/
Plot Attributes: https://docs.juliaplots.org/stable/generated/attributes_plot/
Subplot Attributes: https://docs.juliaplots.org/stable/generated/attributes_subplot/
Axis Attributes: https://docs.juliaplots.org/stable/generated/attributes_axis/

**Comment by t-bltg** [comment]
Sorry, this will be fix by the linked PR.
Until merged, please use the previous release docs e.g. https://docs.juliaplots.org/v1.35/generated/attributes_series/.

**Comment by t-bltg** [comment]
Fixed in `dev`: https://docs.juliaplots.org/dev/generated/attributes_series/

**Comment by rmsmsgood** [comment]
Thank you!
