### ISSUE TITLE
Plotly plot not displaying in tutorial

### ISSUE THREAD

**Issue by Ininterrompue** [JuliaPlots/PlotDocs.jl#321]
See [this](https://docs.juliaplots.org/dev/tutorial/#plotting-backends) page.

**Comment by t-bltg** [comment]
Thanks I probably broke this yesterday.
Let's wait (1h) for the build after https://github.com/JuliaPlots/PlotDocs.jl/commit/e6b000f66693971ad4f39107ac5f943a5db45e83.

**Comment by Ininterrompue** [comment]
[This](https://github.com/JuliaPlots/PlotDocs.jl/pull/164/files#diff-02d45ff3f8228c90514c2aad1ab29383ecadf31cc52bc486fa0c3dbd5bc5145eR122) may be relevant. Not sure why lines 122 and 124 were needed before.

**Comment by t-bltg** [comment]
I've tried something else in https://github.com/JuliaPlots/PlotDocs.jl/commit/c1559ca22b0153fce23c057020eb60153ef2d479 (build in progress).

Because we already do something similar for `plotlyjs`: https://github.com/JuliaPlots/PlotDocs.jl/blob/master/src/PlotDocs.jl#L92-L95

**Comment by t-bltg** [comment]
Ha, probably because `plotly` / `plotlyjs` is trying `html` as best output: https://github.com/JuliaPlots/Plots.jl/blob/master/src/output.jl#L185-L186

**Comment by t-bltg** [comment]
Fixed by https://github.com/JuliaPlots/PlotDocs.jl/commit/56dfcca09bf234be7d431a2cf69e5d4613d4d79a on `dev`.
