### ISSUE TITLE
using Plots; pyplot() breaks docs

### ISSUE THREAD

**Issue by Ininterrompue** [JuliaPlots/PlotDocs.jl#324]
[Reference](https://github.com/JuliaPlots/Plots.jl/blob/fceaf217e59dd4c200491d09608049ba433cd2f8/src/examples.jl#L1239)

[Relevant PR](https://github.com/JuliaPlots/PlotDocs.jl/pull/322) - contour page only has code examples, no generated plots.

**Comment by t-bltg** [comment]
Should be fixed now, by pinning `libgcc-ng` and `libstdcxx-ng`.

See https://discourse.julialang.org/t/glibcxx-version-not-found/82209/13.
