### ISSUE TITLE
Suggestion: a tab with descriptions of seriestypes

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/PlotDocs.jl#54]
There could be a page with Histograms (describing all the functionality there), heatmap/contour-style plots, lines-and-or-markers (perhaps), bars-pies-shapes, 3d plots?
This is by far the most commonly requested documentation item on gitter and elsewhere. Better documented legends is nr 2.

**Comment by JackDevine** [comment]
Sorry if this is obvious, but I am trying to imagine what this would look like.

Will each page just have one backend shown or multiple?

Will we also make it so that there is a text only version of the documentation in the form of a docstring that can be accessed through `?series_type` ?

**Comment by mkborregaard** [comment]
I think just a single backend, for clarity. And yes, we now have capacity to write docstrings for all the `shorthands` defined seriestypes functions https://github.com/JuliaPlots/Plots.jl/issues/1157

**Comment by Ininterrompue** [comment]
I will work on .md's that cover these things. Role model I'll be basing them on is matplotlib's histogram tutorial: 

https://matplotlib.org/stable/gallery/statistics/hist.html
