### ISSUE TITLE
Make plots in examples update interactively

### ISSUE THREAD

**Issue by mkborregaard** [JuliaPlots/PlotDocs.jl#59]
As discussed on Gitter:

if you browse through https://evizero.github.io/Augmentor.jl/ and see figures just take a look the the "Edit on Github" to see how I do it.
all but the "Tutorials" are pretty much vanilla Documenter. The tutorials though are all custom stuff, generated markdown pages by "examples/*.jl" scripts. so unless you want to mess with Weave just ignore those
Christof Stocker
@Evizero
00:30
I actually use Plots to produce the image + gif on this page https://evizero.github.io/Augmentor.jl/gettingstarted/ . forgot about that
Michael Krabbe Borregaard
@mkborregaard
08:33
So you just include an @eval block that creates the image? Sweet.
Christof Stocker
@Evizero
11:00
pretty much yea, and then you include that image in the markdown as usual
you can also use an @example block for this and just end the lines that save the figure with # hide

**Comment by SaschaMann** [comment]
From #80:

> Alternatively we could add all of the figures in our docs to our test examples, and link to those in PlotReferenceImages from here. If we just had a "latest" folder there. In fact, that may be the simplest solution overall.

**Comment by daschw** [comment]
Images are now generated during PlotDocs build. #145 ...

**Comment by mkborregaard** [comment]
<img width="299" alt="Skærmbillede 2019-09-01 kl  09 00 27" src="https://user-images.githubusercontent.com/8429802/64071953-fe974d00-cc96-11e9-98e1-2034545ff79d.png">
