### ISSUE TITLE
Suggestion: generate plots while building the docs

### ISSUE THREAD

**Issue by piever** [JuliaPlots/PlotDocs.jl#79]
I'm not sure how feasible it is, especially if we want to do it for all the backends,  but I've noticed that in JuliaDB the plots in the documentation are generated while building the documentation. So for example [this page](https://github.com/JuliaComputing/JuliaDB.jl/blob/master/docs/src/api/plotting.md) generates [this page](http://juliadb.org/latest/api/plotting.html). I think it's a very nice way of making sure that the docs are always accurate. On the other hand getting all backends to work remotely may be a tough challenge, but the "backend independent" docs could potentially be done like this (and the default backend as well).

**Comment by ChrisRackauckas** [comment]
Duplicate of https://github.com/JuliaPlots/PlotDocs.jl/issues/59 ?

**Comment by piever** [comment]
I'm really not sure how I could miss an identical issue out of a grand total of 12 open issues... Sorry about the noise! Hope at least the linked example is a good inspiration on how to do this in practice.

**Comment by ChrisRackauckas** [comment]
We probably need to rename the other issue, and yes this is a great example of how to do it!
