### ISSUE TITLE
arg_desc.jl of Plots contains more attribute descriptions than PlotDocs

### ISSUE THREAD

**Issue by t37w** [JuliaPlots/PlotDocs.jl#87]
The KW dict in file https://github.com/JuliaPlots/Plots.jl/blob/master/src/arg_desc.jl contains more attribute descriptions than the PlotDocs tables in the online WEB view of http://docs.juliaplots.org/latest/attributes/.
For example I searched for the attribute 'camera' which is not available in table for subplots.

**Comment by mkborregaard** [comment]
These tables are generated by this code https://github.com/JuliaPlots/PlotDocs.jl/blob/master/src/PlotDocs.jl#L228-L240 
@ChrisRackauckas do you know if these are set up to be run automatically every time Documenter rebuilds the site?

**Comment by ChrisRackauckas** [comment]
I don't think so?

**Comment by mkborregaard** [comment]
OK

**Comment by daschw** [comment]
Fixed in #106
